package com.suraj.authsphere.audit.domain;

public enum AuditEventType {
    USER_REGISTERED,
    USER_REGISTRATION_FAILED,
    USER_LOGIN_SUCCEEDED,
    USER_LOGIN_FAILED,
    TOKEN_REFRESH_SUCCEEDED,
    TOKEN_REFRESH_FAILED,
    USER_LOGOUT,
    USER_LOGOUT_ALL,
    SESSION_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    BIOMETRIC_ENROLL_STARTED,
    BIOMETRIC_ENROLLED,
    BIOMETRIC_LOGIN_SUCCEEDED,
    BIOMETRIC_LOGIN_FAILED,
    BIOMETRIC_CREDENTIAL_REVOKED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    PERMISSION_CREATED,
    PERMISSION_UPDATED,
    PERMISSION_DELETED,
    ROLE_ASSIGNED_TO_USER,
    ROLE_REMOVED_FROM_USER,
    PERMISSION_ASSIGNED_TO_ROLE,
    PERMISSION_REMOVED_FROM_ROLE,
    API_REQUEST_FAILED
}

